Add a macos-arm build

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -64,10 +64,47 @@ jobs:
           sudo installer -pkg ./sac2c-basic.pkg -target /
           sac2c -V
       - name: Set XCode version
+        uses: maxim-lobanov/setup-xcode@v1
+        with:
+          xcode-version: '14.1'
+      - name: Create build dir
         run: |
-          sudo xcode-select -switch "/Applications/Xcode_14.1.0.app"
-          # we need to rewrite sysroot path to use specific Xcode version
-          sudo find /usr/local/share -type f -name 'sac2crc_*' -execdir sed -i.bak 's/Xcode\.app/Xcode_14\.1\.0\.app/g' {} \;
+          cmake -E make_directory ${{runner.workspace}}/build
+          mkdir $HOME/.sac2crc
+      - name: Configure build-system
+        shell: bash
+        working-directory: ${{runner.workspace}}/build
+        run: cmake -DFULLTYPES=ON ${GITHUB_WORKSPACE}
+      - name: Build
+        shell: bash
+        working-directory: ${{runner.workspace}}/build
+        run: |
+          cmake --build . -j 2 2>&1 | tee build.log
+          if [ ${PIPESTATUS[0]} -ne 0 ]; then
+            echo "!!! ERROR detected in build !!!";
+            exit 1;
+          fi
+          ${GITHUB_WORKSPACE}/ci/fail-on-warning.sh build.log
+  # MacOS (arm)
+  build-macos-arm:
+    runs-on: macos-15
+    steps:
+      - name: Get HEAD and submodules
+        uses: actions/checkout@v2
+        with:
+          # we need to get tag information
+          fetch-depth: 0
+          # we need to get all submodules
+          submodules: 'recursive'
+      - name: Install sac2c-basic
+        run: |
+          wget ${BASE_URL}/MacOS_arm64/sac2c-basic.pkg
+          sudo installer -pkg ./sac2c-basic.pkg -target /
+          sac2c -V
+      - name: Set XCode version
+        uses: maxim-lobanov/setup-xcode@v1
+        with:
+          xcode-version: '16.2'
       - name: Create build dir
         run: |
           cmake -E make_directory ${{runner.workspace}}/build
